README.md
main.tf
module.yaml
output.tf
variables.tf

Added Root module & meta data yaml file

Added Root module & meta data yaml file

---

.github/workflows/release.yml
.releaserc

Added a releaserc file for the semantic-release module, and added a conditional statement to the release workflow to only execute if the CI workflow was successful
**Tick the relevant boxes:**
Merge using "Squash and merge" and ensure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message based on the PR contents (this ultimately determines if a new version of the modules needs to be released, and if so, which semver number should be used).

chore: add sem-ver file and workflow condition

---

.github/workflows/ci.yml
.github/workflows/release.yml

consume common pipeline from common-pipeline-assets repo
**Tick the relevant boxes:**
Merge using "Squash and merge" and ensure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message based on the PR contents (this ultimately determines if a new version of the modules needs to be released, and if so, which semver number should be used).

ci: consume common pipeline from common-pipeline-assets repo

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
tests/README.md

Update readme files and PR template to conform more closely to IBM style.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
**Tick the relevant boxes:**
Merge using "Squash and merge" and ensure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message based on the PR contents (this ultimately determines if a new version of the modules needs to be released, and if so, which semver number should be used).

minor editorial updates

---

examples/non-default/README.md

docs: fix typo

---

README.md

Update Examples section of README

docs: Update Examples section of README

---

README.md

Update guidance for the usage section in the readme file not to use `var.xx` or other placeholder values for the input variables. These values don't provide a clear understanding about what can be passed in. 
Also add text to use when no permissions are required

docs: update guidance

---

tests/pr_test.go

use geretain-test-resources RG

test: use geretain-test-resources RG

---

tests/README.md
tests/pr_test.go

update submodule to use common-dev-assets tests code

feat: update submodule to use common-dev-assets tests code

---

.github/workflows/ci.yml
.github/workflows/release.yml

update the workflows
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the …

ci: update workflows

---

.github/workflows/ci.yml

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional …

fix: use sha

---

.github/workflows/ci.yml

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional …

fix: use rc

---

.github/workflows/ci.yml
.github/workflows/release.yml
.secrets.baseline

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional …

ci: update pipeline version

---

.github/workflows/ci.yml

If the CI pipeline doesn't run when you …

temp test pipeline

---

.github/workflows/ci.yml
.github/workflows/release.yml

If the CI pipeline doesn't run when you …

Update pipeline version

---

.github/settings.yml

Update settings.yml with topics
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a …

Update settings.yml with topics

---

.github/workflows/ci.yml
.github/workflows/release.yml

bump to latest pipeline version
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a …

ci: bump to latest pipeline version

---

.github/workflows/ci.yml
.github/workflows/release.yml
cra-config.yaml

Due to SCC api changes, the values in cra-config.yaml need to change
Run the CI pipeline when the PR is ready for review …

Update pipeline + cra-config.yaml

---

README.md

Add tf submodule hook tag to README
Run the CI pipeline when the PR is ready for review and you expect tests to pass. …

docs: add tf submodule hook tag

---

README.md
examples/basic/version.tf
examples/complete/version.tf
module-metadata.json
version.tf

If the CI pipeline doesn't run when you …

ci: updates to mod template

---

README.md

Reverts terraform-ibm-modules/terraform-ibm-module-template#592

Revert "docs: add tf submodule hook tag"

---

README.md

Add TOC and move examples section
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add …

docs: add toc and update examples

---

README.md

Add overview
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR …

docs: add overview

---

README.md

If the CI pipeline doesn't run when you …

docs: remove examples section

---

.github/settings.yml

```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

add topics by default

---

README.md

correct link in readme doc
```
/run pipeline
```

docs: correct link in readme doc

---

README.md

Seemed to have indentation issues, and also roles were reversed. 
```
/run pipeline
```

Update "Required IAM access policies" template

---

.gitignore

Add basic Golang entries to the gitignore file (used common golang block from https://www.toptal.com/developers/gitignore).
```
/run pipeline
```

chore: gitignore golang additions

---

outputs.tf

fix typo in outputs

---

.secrets.baseline
README.md

Removed reference architectures related comment in README
https://github.ibm.com/GoldenEye/issues/issues/15302
```
/run pipeline
```

docs: removed reference architectures section
